// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title CertificateRegistry
 * @dev Yovaan AI – Decentralized Certificate Authentication System
 * @notice Issues, verifies, and revokes blockchain-anchored certificates
 */
contract CertificateRegistry is Ownable, ReentrancyGuard {

    constructor() Ownable(msg.sender) {}

    // ─────────────────────────────────────────────
    //  STRUCTS
    // ─────────────────────────────────────────────

    struct Certificate {
        string  certId;       // Unique certificate identifier
        string  hash;         // SHA-256 hash of the PDF file
        string  cid;          // IPFS Content Identifier
        address issuer;       // Wallet that issued this cert
        address student;      // Recipient wallet
        uint256 timestamp;    // Block timestamp of issuance
        bool    revoked;      // Revocation flag
        string  metadata;     // JSON string: name, course, grade, etc.
    }

    // ─────────────────────────────────────────────
    //  STATE
    // ─────────────────────────────────────────────

    /// @dev certId → Certificate
    mapping(string => Certificate) private certificates;

    /// @dev Wallets permitted to call issueCertificate()
    mapping(address => bool) public authorizedIssuers;

    /// @dev student wallet → list of certIds they own
    mapping(address => string[]) public studentCertificates;

    /// @dev Track existence to avoid silent overwrites
    mapping(string => bool) private certExists;

    // ─────────────────────────────────────────────
    //  EVENTS
    // ─────────────────────────────────────────────

    event IssuerAdded(address indexed issuer);
    event IssuerRemoved(address indexed issuer);
    event CertificateIssued(
        string indexed certId,
        address indexed issuer,
        address indexed student,
        uint256 timestamp
    );
    event CertificateRevoked(string indexed certId, address indexed revokedBy);

    // ─────────────────────────────────────────────
    //  MODIFIERS
    // ─────────────────────────────────────────────

    modifier onlyAuthorizedIssuer() {
        require(authorizedIssuers[msg.sender], "CertReg: Not an authorized issuer");
        _;
    }

    modifier certMustExist(string memory _certId) {
        require(certExists[_certId], "CertReg: Certificate does not exist");
        _;
    }

    // ─────────────────────────────────────────────
    //  ISSUER MANAGEMENT (Owner only)
    // ─────────────────────────────────────────────

    /**
     * @notice Grants issuance rights to a wallet
     * @param _issuer Wallet address to authorize
     */
    function addIssuer(address _issuer) external onlyOwner {
        require(_issuer != address(0), "CertReg: Zero address");
        require(!authorizedIssuers[_issuer], "CertReg: Already authorized");
        authorizedIssuers[_issuer] = true;
        emit IssuerAdded(_issuer);
    }

    /**
     * @notice Revokes issuance rights from a wallet
     * @param _issuer Wallet address to deauthorize
     */
    function removeIssuer(address _issuer) external onlyOwner {
        require(authorizedIssuers[_issuer], "CertReg: Not authorized");
        authorizedIssuers[_issuer] = false;
        emit IssuerRemoved(_issuer);
    }

    // ─────────────────────────────────────────────
    //  CERTIFICATE ISSUANCE
    // ─────────────────────────────────────────────

    /**
     * @notice Issues a new certificate on-chain
     * @param _certId     Unique cert ID generated by backend (UUID-based)
     * @param _hash       SHA-256 hash of the PDF
     * @param _cid        IPFS CID where the PDF is pinned
     * @param _student    Recipient's wallet address
     * @param _metadata   JSON string with human-readable cert fields
     */
    function issueCertificate(
        string  memory _certId,
        string  memory _hash,
        string  memory _cid,
        address        _student,
        string  memory _metadata
    ) external onlyAuthorizedIssuer nonReentrant {
        require(bytes(_certId).length > 0,  "CertReg: Empty certId");
        require(bytes(_hash).length  == 64, "CertReg: Invalid SHA-256 hash length");
        require(bytes(_cid).length   > 0,   "CertReg: Empty CID");
        require(_student != address(0),      "CertReg: Zero student address");
        require(!certExists[_certId],        "CertReg: Certificate already exists");

        certificates[_certId] = Certificate({
            certId:    _certId,
            hash:      _hash,
            cid:       _cid,
            issuer:    msg.sender,
            student:   _student,
            timestamp: block.timestamp,
            revoked:   false,
            metadata:  _metadata
        });

        certExists[_certId] = true;
        studentCertificates[_student].push(_certId);

        emit CertificateIssued(_certId, msg.sender, _student, block.timestamp);
    }

    // ─────────────────────────────────────────────
    //  REVOCATION
    // ─────────────────────────────────────────────

    /**
     * @notice Marks a certificate as revoked (irreversible)
     * @param _certId Certificate to revoke
     */
    function revokeCertificate(string memory _certId)
        external
        onlyAuthorizedIssuer
        certMustExist(_certId)
    {
        Certificate storage cert = certificates[_certId];
        require(!cert.revoked, "CertReg: Already revoked");
        require(cert.issuer == msg.sender || owner() == msg.sender,
            "CertReg: Only original issuer or owner can revoke");

        cert.revoked = true;
        emit CertificateRevoked(_certId, msg.sender);
    }

    // ─────────────────────────────────────────────
    //  READ FUNCTIONS
    // ─────────────────────────────────────────────

    /**
     * @notice Fetches full certificate data
     * @param _certId Certificate to look up
     */
    function getCertificate(string memory _certId)
        external
        view
        certMustExist(_certId)
        returns (Certificate memory)
    {
        return certificates[_certId];
    }

    /**
     * @notice Returns all certIds owned by a student wallet
     * @param _student Student wallet address
     */
    function getStudentCertificates(address _student)
        external
        view
        returns (string[] memory)
    {
        return studentCertificates[_student];
    }

    /**
     * @notice Quick existence + validity check
     * @param _certId Certificate to check
     * @return exists    Whether it exists
     * @return revoked   Whether it has been revoked
     */
    function checkCertificate(string memory _certId)
        external
        view
        returns (bool exists, bool revoked)
    {
        exists  = certExists[_certId];
        revoked = exists ? certificates[_certId].revoked : false;
    }
}
